apiVersion: v1
kind: Node
metadata:
  annotations:
    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2021-01-28T16:06:09Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: minikube
    kubernetes.io/os: linux
    minikube.k8s.io/commit: 7e8b5a89575945ba8f8246bfe547178c1a995198
    minikube.k8s.io/name: minikube
    minikube.k8s.io/updated_at: 2021_01_28T10_06_11_0700
    minikube.k8s.io/version: v1.17.0
    node-role.kubernetes.io/control-plane: ""
    node-role.kubernetes.io/master: ""
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:volumes.kubernetes.io/controller-managed-attach-detach: {}
        f:labels:
          .: {}
          f:beta.kubernetes.io/arch: {}
          f:beta.kubernetes.io/os: {}
          f:kubernetes.io/arch: {}
          f:kubernetes.io/hostname: {}
          f:kubernetes.io/os: {}
      f:status:
        f:addresses:
          .: {}
          k:{"type":"Hostname"}:
            .: {}
            f:address: {}
            f:type: {}
          k:{"type":"InternalIP"}:
            .: {}
            f:address: {}
            f:type: {}
        f:allocatable:
          .: {}
          f:cpu: {}
          f:ephemeral-storage: {}
          f:hugepages-2Mi: {}
          f:memory: {}
          f:pods: {}
        f:capacity:
          .: {}
          f:cpu: {}
          f:ephemeral-storage: {}
          f:hugepages-2Mi: {}
          f:memory: {}
          f:pods: {}
        f:conditions:
          .: {}
          k:{"type":"DiskPressure"}:
            .: {}
            f:lastHeartbeatTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"MemoryPressure"}:
            .: {}
            f:lastHeartbeatTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"PIDPressure"}:
            .: {}
            f:lastHeartbeatTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastHeartbeatTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:daemonEndpoints:
          f:kubeletEndpoint:
            f:Port: {}
        f:images: {}
        f:nodeInfo:
          f:architecture: {}
          f:bootID: {}
          f:containerRuntimeVersion: {}
          f:kernelVersion: {}
          f:kubeProxyVersion: {}
          f:kubeletVersion: {}
          f:machineID: {}
          f:operatingSystem: {}
          f:osImage: {}
          f:systemUUID: {}
    manager: kubelet
    operation: Update
    time: "2021-01-28T16:06:09Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubeadm.alpha.kubernetes.io/cri-socket: {}
        f:labels:
          f:node-role.kubernetes.io/control-plane: {}
          f:node-role.kubernetes.io/master: {}
    manager: kubeadm
    operation: Update
    time: "2021-01-28T16:06:11Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:minikube.k8s.io/commit: {}
          f:minikube.k8s.io/name: {}
          f:minikube.k8s.io/updated_at: {}
          f:minikube.k8s.io/version: {}
    manager: kubectl-label
    operation: Update
    time: "2021-01-28T16:06:12Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:node.alpha.kubernetes.io/ttl: {}
      f:spec:
        f:podCIDR: {}
        f:podCIDRs:
          .: {}
          v:"10.244.0.0/24": {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-01-28T16:06:27Z"
  name: minikube
  resourceVersion: "2916"
  uid: 27fedb67-cac8-4a50-b830-08a6c3f20974
spec:
  podCIDR: 10.244.0.0/24
  podCIDRs:
  - 10.244.0.0/24
status:
  addresses:
  - address: 192.168.33.8
    type: InternalIP
  - address: minikube
    type: Hostname
  allocatable:
    cpu: "4"
    ephemeral-storage: 17784752Ki
    hugepages-2Mi: "0"
    memory: 5952468Ki
    pods: "110"
  capacity:
    cpu: "4"
    ephemeral-storage: 17784752Ki
    hugepages-2Mi: "0"
    memory: 5952468Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2021-01-28T16:53:25Z"
    lastTransitionTime: "2021-01-28T16:06:06Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2021-01-28T16:53:25Z"
    lastTransitionTime: "2021-01-28T16:06:06Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2021-01-28T16:53:25Z"
    lastTransitionTime: "2021-01-28T16:06:06Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2021-01-28T16:53:25Z"
    lastTransitionTime: "2021-01-28T16:06:22Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - quay.io/keycloak/keycloak@sha256:13a000cc24eefb105848fe1f76706e4b9a2a52ecf1052db1ac98389ec2038cfe
    - quay.io/keycloak/keycloak:12.0.2
    sizeBytes: 639811134
  - names:
    - us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller@sha256:46ba23c3fbaafd9e5bd01ea85b2f921d9f2217be082580edc22e6c704a83f02f
    - us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2
    sizeBytes: 285704097
  - names:
    - k8s.gcr.io/etcd@sha256:4ad90a11b55313b182afc186b9876c8e891531b8db4c9bf1541953021618d0e2
    - k8s.gcr.io/etcd:3.4.13-0
    sizeBytes: 253392289
  - names:
    - kubernetesui/dashboard@sha256:7f80b5ba141bead69c4fee8661464857af300d7d7ed0274cf7beecedc00322e6
    - kubernetesui/dashboard:v2.1.0
    sizeBytes: 225733746
  - names:
    - k8s.gcr.io/kube-apiserver@sha256:465ba895d578fbc1c6e299e45689381fd01c54400beba9e8f1d7456077411411
    - k8s.gcr.io/kube-apiserver:v1.20.2
    sizeBytes: 121669114
  - names:
    - k8s.gcr.io/kube-proxy@sha256:326fe8a4508a5db91cf234c4867eff5ba458bc4107c2a7e15c827a74faa19be9
    - k8s.gcr.io/kube-proxy:v1.20.2
    sizeBytes: 118400203
  - names:
    - k8s.gcr.io/kube-controller-manager@sha256:842a071d4ad49b0018f7f7404ac8a4ddfc2bce2ce15b3f8131d89563fda36c9b
    - k8s.gcr.io/kube-controller-manager:v1.20.2
    sizeBytes: 115852794
  - names:
    - jettech/kube-webhook-certgen@sha256:ff01fba91131ed260df3f3793009efbf9686f5a5ce78a85f81c386a4403f7689
    - jettech/kube-webhook-certgen:v1.3.0
    sizeBytes: 54697790
  - names:
    - jettech/kube-webhook-certgen@sha256:da8122a78d7387909cf34a0f34db0cce672da1379ee4fd57c626a4afe9ac12b7
    - jettech/kube-webhook-certgen:v1.2.2
    sizeBytes: 49003629
  - names:
    - k8s.gcr.io/kube-scheduler@sha256:304b3d70497bd62498f19f82f9ef164d38948e5ae94966690abfe9d1858867e2
    - k8s.gcr.io/kube-scheduler:v1.20.2
    sizeBytes: 46384634
  - names:
    - k8s.gcr.io/coredns@sha256:73ca82b4ce829766d4f1f10947c3a338888f876fbed0540dc849c89ff256e90c
    - k8s.gcr.io/coredns:1.7.0
    sizeBytes: 45227747
  - names:
    - kubernetesui/metrics-scraper@sha256:555981a24f184420f3be0c79d4efb6c948a85cfce84034f85a563f4151a81cbf
    - kubernetesui/metrics-scraper:v1.0.4
    sizeBytes: 36937728
  - names:
    - gcr.io/k8s-minikube/storage-provisioner@sha256:06f83c679a723d938b8776510d979c69549ad7df516279981e23554b3e68572f
    - gcr.io/k8s-minikube/storage-provisioner:v4
    sizeBytes: 29683712
  - names:
    - k8s.gcr.io/pause@sha256:927d98197ec1141a368550822d18fa1c60bdae27b78b0c004f705f548c07814f
    - k8s.gcr.io/pause:3.2
    sizeBytes: 682696
  nodeInfo:
    architecture: amd64
    bootID: 8bc886fe-f527-4bec-8496-1e724852da17
    containerRuntimeVersion: docker://20.10.2
    kernelVersion: 4.19.157
    kubeProxyVersion: v1.20.2
    kubeletVersion: v1.20.2
    machineID: c023f83c52eb4d1d8de9b71c61aca087
    operatingSystem: linux
    osImage: Buildroot 2020.02.8
    systemUUID: a60411eb-0000-0000-ac9b-acde48001122
