language: android
android:
  components:
    - build-tools-27.0.3
    - android-27
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install:
  - openssl aes-256-cbc -K $encrypted_cbbc966ea4f0_key -iv $encrypted_cbbc966ea4f0_iv
    -in release-keystore.jks.enc -out release-keystore.jks -d
