source 'https://cdn.cocoapods.org'
platform :ios, '11.0'

target 'Tidepool' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.14.2",
    :subspecs => [
      "Core"
    ],
    :inhibit_warnings => true

  # Install unimodules
  require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
  use_unimodules!(
    modules_paths: ['../node_modules'],
    exclude: [
      'expo-face-detector',
      'expo-payments-stripe',
      'expo-ads-admob',
      'expo-ads-facebook',
      'expo-analytics-amplitude',
      'expo-analytics-segment',
      'expo-app-auth',
      'expo-av',
      'expo-background-fetch',
      'expo-barcode-scanner',
      'expo-brightness',
      'expo-calendar',
      'expo-camera',
      'expo-contacts',
      'expo-crypto',
      'expo-document-picker',
      'expo-facebook',
      'expo-google-sign-in',
      'expo-haptics',
      'expo-image-manipulator',
      'expo-image-picker',
      'expo-intent-launcher',
      'expo-local-authentication',
      'expo-localization',
      # 'expo-location', # Need to keep this for now since there's a runtime dependency on it (even though we don't use it)
      'expo-media-library',
      'expo-print',
      'expo-random',
      'expo-secure-store',
      'expo-sensors',
      'expo-sharing',
      'expo-sms',
      'expo-speech',
      'expo-sqlite',
      'expo-task-manager',
      'expo-web-browers',
      'expo-barcode-scanner-interface',
      'expo-camera-interface'
    ],
  )

  # Install React Native and its dependencies
  require_relative '../node_modules/react-native/scripts/autolink-ios.rb'
  use_react_native!

  pod 'RollbarReactNative', :path => '../node_modules/rollbar-react-native'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'TPHealthKitUploader', :git => 'https://github.com/tidepool-org/healthkit-uploader', :tag => '1.0.9'
  pod 'SwiftyJSON', '5.0.0'
  pod 'CocoaLumberjack/Swift', '3.5.3'
  pod 'Alamofire', '4.9.1'
  pod 'Zip', '1.1.0'
  pod 'CSV.swift', '2.4.3'

  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|

      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end

      if pod_name == 'ExpoKit'
        target_installation_result.native_target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'

          # Enable Google Maps support
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HAVE_GOOGLE_MAPS=1'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HAVE_GOOGLE_MAPS_UTILS=1'

        end
      end

      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end


      # Can't specify this in the React podspec because we need to use those podspecs for detached
      # projects which don't reference ExponentCPP.
      if pod_name.start_with?('React')
        target_installation_result.native_target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
          config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        end
      end

      # Build React Native with RCT_DEV enabled and RCT_ENABLE_INSPECTOR and
      # RCT_ENABLE_PACKAGER_CONNECTION disabled
      next unless pod_name == 'React'
      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
      end
    end
  end
end
