const ADD_COMMENT_ROUTE_NAME = "ADD_COMMENT_ROUTE_NAME";
const ADD_NOTE_ROUTE_NAME = "ADD_NOTE_ROUTE_NAME";
const DEBUG_SETTINGS_ROUTE_NAME = "DEBUG_SETTINGS_ROUTE_NAME";
const EDIT_COMMENT_ROUTE_NAME = "EDIT_COMMENT_ROUTE_NAME";
const EDIT_NOTE_ROUTE_NAME = "EDIT_NOTE_ROUTE_NAME";
const HOME_ROUTE_NAME = "HOME_ROUTE_NAME";
const LAUNCH_ROUTE_NAME = "LAUNCH_ROUTE_NAME";
const MAIN_DRAWER_ROUTE_NAME = "MAIN_DRAWER_ROUTE_NAME";
const SIGN_IN_ROUTE_NAME = "SIGN_IN_ROUTE_NAME";
const SIGN_UP_ROUTE_NAME = "SIGN_UP_ROUTE_NAME";
const SIGN_UP_CREATE_ACCOUNT_ROUTE_NAME = "SIGN_UP_CREATE_ACCOUNT_ROUTE_NAME";
const SIGN_UP_CREATE_ACCOUNT_PERSONAL_ROUTE_NAME = "SIGN_UP_CREATE_ACCOUNT_PERSONAL_ROUTE_NAME";
const SIGN_UP_CREATE_ACCOUNT_CLINICIAN_ROUTE_NAME = "SIGN_UP_CREATE_ACCOUNT_CLINICIAN_ROUTE_NAME";
const SIGN_UP_CLINICIAN_SETUP_ROUTE_NAME = "SIGN_UP_CLINICIAN_SETUP_ROUTE_NAME";
const SIGN_UP_TERMS_OF_USE_ROUTE_NAME = "SIGN_UP_TERMS_OF_USE_ROUTE_NAME";
const SIGN_UP_DIABETES_DETAILS_ROUTE_NAME =
  "SIGN_UP_DIABETES_DETAILS_ROUTE_NAME";
const SIGN_UP_DIABETES_DETAILS_TWO_ROUTE_NAME =
  "SIGN_UP_DIABETES_DETAILS_TWO_ROUTE_NAME";
const SIGN_UP_ACTIVATE_ACCOUNT_ROUTE_NAME =
  "SIGN_UP_ACTIVATE_ACCOUNT_ROUTE_NAME";
const SWITCH_PROFILE_ROUTE_NAME = "SWITCH_PROFILE_ROUTE_NAME";

export {
  ADD_COMMENT_ROUTE_NAME,
  ADD_NOTE_ROUTE_NAME,
  DEBUG_SETTINGS_ROUTE_NAME,
  EDIT_COMMENT_ROUTE_NAME,
  EDIT_NOTE_ROUTE_NAME,
  HOME_ROUTE_NAME,
  LAUNCH_ROUTE_NAME,
  MAIN_DRAWER_ROUTE_NAME,
  SIGN_IN_ROUTE_NAME,
  SIGN_UP_ROUTE_NAME,
  SIGN_UP_CREATE_ACCOUNT_ROUTE_NAME,
  SIGN_UP_CREATE_ACCOUNT_CLINICIAN_ROUTE_NAME,
  SIGN_UP_CREATE_ACCOUNT_PERSONAL_ROUTE_NAME,
  SIGN_UP_CLINICIAN_SETUP_ROUTE_NAME,
  SIGN_UP_TERMS_OF_USE_ROUTE_NAME,
  SIGN_UP_DIABETES_DETAILS_ROUTE_NAME,
  SIGN_UP_DIABETES_DETAILS_TWO_ROUTE_NAME,
  SIGN_UP_ACTIVATE_ACCOUNT_ROUTE_NAME,
  SWITCH_PROFILE_ROUTE_NAME,
};
